### ISSUE TITLE
no longer works on v45 of the game

### ISSUE THREAD

**Issue by g7755726** [gamendegamer321/Lethal-Admin#1]
it tries to load but nothing shows due to new v45 update

**Comment by gamendegamer321** [comment]
I have not had this issue myself with any of the versions of lethal admin.
Could you check that you have properly installed the newest version of the mod? (v1.0.6)
And do you have problems with other mods?

If you manually installed lethal admin, the mod should be at `path_to_lethal_company/BepInEx/Plugins/LethalAdmin.dll`.
If you are using a modmanager check that it is in your modlist and you restarted your game after installing.

**Comment by gamendegamer321** [comment]
Cannot reproduce the issue, feel free to reopen this if the issue persists!
