### ISSUE TITLE
[Feature Request] Host Only Furniture Move

### ISSUE THREAD

**Issue by Sourceshard** [gamendegamer321/Lethal-Admin#10]
Limit the host as the only one that can move any placeable on the ship.

**Comment by gamendegamer321** [comment]
Alright so I've looked into this and already got a working solution to prevent other players (so everybody except the host) from moving around placeables and prevent them from being moved into the storage.
The only thing that is still possible is removing items from the storage back into the ship, I'm currently seeing if it's also possible to limit that to the host.
