### ISSUE TITLE
[Bug Report] Lever Lock

### ISSUE THREAD

**Issue by Sourceshard** [gamendegamer321/Lethal-Admin#11]
It appears when another player uses another way to interact with the lever instead of walking up to it and pulling it, it locks into the pulled position with the hover over text saying "Waiting for the ship to land". As Lethal-Admin denies the land initiation the lever is uninteractible and the save has to be relaunched. I tested this with [ExtraTerminalCommands by Beauver]. However I imagine this will work for any mod that tried to make the call to launch. You may need to have your mod catch and deny any calls to land the ship through any means other than the host.

https://thunderstore.io/c/lethal-company/p/Beauver/ExtraTerminalCommands/

**Comment by gamendegamer321** [comment]
Ah I'll look into it, you should already be able to disable the feature in the config file or settings tab.
Currently I use a small "trick" where the lever starts the game differently depending on if you are the host or not, I assume the plugins just use the method that works for all clients (which I block). I'll have to see if this is even possible or you simply have to disable the feature when using other mods that interact with the lever.

Just a few questions to help me:
Was the leverLock enabled when the bug occured?
Was the host also not able to pull the lever using the ExtraTerminalCommands?

**Comment by Sourceshard** [comment]
Just a few questions to help me:
Was the leverLock enabled when the bug occured? - Yes
Was the host also not able to pull the lever using the ExtraTerminalCommands? - Yes

**Comment by gamendegamer321** [comment]
I have just tried reproducing the problem, but for me the command works as expected with the leverLock enabled, the host is able the make the ship depart while the other players are not (except when on a moon, there all players are able to make the ship depart).

Is it possible for you to check in the **Settings & Logs** tab if a log like this is created?
 > [Start Game] Blocked bypass attempt on Server

And did you also have other mods installed when the problem occurred?

**Comment by Sourceshard** [comment]
Yes, I have a pretty extensive mod pack that I was testing it on. I had believed it to be Admin Tweaks but it may be conflictions with another mod. I will retest again as I make daily changes to the pack. So the test environment changes frequently. I had an anti-cheat mod that may have been stopping it from working that I have since gotten rid of. I will check and post an updated reply.

**Comment by gamendegamer321** [comment]
Unable to reproduce, if you have more information feel free to reopen this!
