### ISSUE TITLE
[Feature Request] Collapsible Window and Closable Window

### ISSUE THREAD

**Issue by Sourceshard** [gamendegamer321/Lethal-Admin#13]
I would love it if there was a Minimise line on the top right [ -- ]. This minimize line would collapse the window into a bar so that it take up less real estate. Also providing an [ X ] to close the window entirely and bring it up with a keybinding or a button present in the ESC menu would be a wonderful addition.

**Comment by gamendegamer321** [comment]
I'll see what I can do, I don't think this is something supported by default so I might need to get a bit creative.
For the keybinds I'm a bit hesitant as I was already having problems with some other mods and their keybinds, so it might be that I decide not to do only the minimisation.

**Comment by Sourceshard** [comment]
Roger. Message me here or on the Modding Discord if you need any testing.
