### ISSUE TITLE
Nameless people allowed to join

### ISSUE THREAD

**Issue by JobyGitGud** [gamendegamer321/Lethal-Admin#14]
No idea why but I'll be rolling back to 1.3 for a while till I get some time too look into it but nameless people are suddenly allowed to join since 1.5 I think. (possibly since 1.4).

I'll look into the code later if nobody else does when I find the time.

**Comment by gamendegamer321** [comment]
Oh weird, there shouldn't be any changes to that since v1.3.0 but I'll check if I have the time.
I assume you mean players joining with an empty steam ID (0@steam)? They should still be blocked if you have **require steam** enabled.

**Comment by JobyGitGud** [comment]
I did see a user with 0@steam ID (namesless) and we could see him in the void somewhere on the screen where you can select players to teleport. 

So it was your typical flying around cheater who pops heads and makes people say things with their name via chat.

I may have to attempt to re-produce later if you don't manage to test it however you do.

Busy with new job, so only time to play in the evenings (when I feel like it.).

Hope this info helps.

**Comment by gamendegamer321** [comment]
Should now be fixed with the new approval system
