### ISSUE TITLE
[Conflict Issue] one vote call autopilot host feature are blocked by HostFixes

### ISSUE THREAD

**Issue by CoolLKKPS** [gamendegamer321/Lethal-Admin#16]
that's not HostFixes issues but i hope can looking for compatibility solutions, no matter Lethal_Admin or AntiCheat, all related this feature are malfunction

**Comment by CoolLKKPS** [comment]
https://github.com/Charlese2/HostFixes/issues/11

**Comment by gamendegamer321** [comment]
Ah, I'll look into it as it is implemented a bit like a cheat so I'm not really surprised.

**Comment by gamendegamer321** [comment]
I've changed how it works and (at least for me) it works now with HostFixes. I'll probably release it this weekend (I still have some things I want to add and test)
