### ISSUE TITLE
Playing in LAN mode attempts to kick the player if RequireSteam is enabled

### ISSUE THREAD

**Issue by jverif** [gamendegamer321/Lethal-Admin#17]
This mod will attempt to kick a LAN player (even the host) if they join while the "RequireSteam" setting is enabled. Could this setting potentially be ignored if in LAN mode? I ran into this testing my mod in a modpack, and I usually use LAN since it's a little bit faster to initialize.

![image](https://github.com/gamendegamer321/Lethal-Admin/assets/22532950/ead66255-b5f3-4da9-8eb9-c6f133e84786)

It sent me on a little bit of a hunt a minute ago, because this apparently causes unity to try to delete objects that player has "ownership" of, which included some default unlockables that my mod adds.

![image](https://github.com/gamendegamer321/Lethal-Admin/assets/22532950/c82d3a49-bf3e-47f1-9b3f-65d7edf26b8a)

**Comment by gamendegamer321** [comment]
I've added a check for LAN-mode, I will probably update the mod this weekend as there are still some things I want to add and that need to be tested. (Part of it is making it possible to decline connections so I don't need to kick them after joining, which hopefully also means that you no longer have the problem of unity trying to delete objects)
