### ISSUE TITLE
Preemptive Ban System for Game Disruptors

### ISSUE THREAD

**Issue by snipeTR** [gamendegamer321/Lethal-Admin#18]
**Please implement a shared ban system. Some people are really malicious and need to be banned for various legitimate reasons. I am providing a list of Turkish players who should be banned here. It would be great if there was a common pool and if someone was banned by, for example, 10 people, they would be banned by everyone using this mod. This way, people will be punished for ruining the game.**

C:\Users\\%username%\AppData\Roaming\Thunderstore Mod manager\DataFolder\LethalCompany\profiles\modlar\BepInEx\config\gamendegamer.lethaladmin.json

`{"Bans":[{"SteamID":76561199582334026,"Username":"zastiwar","BanReason":"No reason given"},{"SteamID":76561198081340654,"Username":"MiracKuyumcu","BanReason":"oç"},{"SteamID":76561199027040517,"Username":"Error","BanReason":"hile"},{"SteamID":76561199494940106,"Username":"RevolZ","BanReason":"hile"},{"SteamID":76561199087968623,"Username":"Umut","BanReason":"oyunbozan"},{"SteamID":76561198966511211,"Username":"HeehoTheWitch","BanReason":"troll ban açma"},{"SteamID":76561198145489810,"Username":"Muera","BanReason":"mal hileci"},{"SteamID":76561199316022088,"Username":"oguz","BanReason":"test"},{"SteamID":76561199482390986,"Username":"Spunk","BanReason":"oç"},{"SteamID":76561198123605962,"Username":"LordOfTheRings","BanReason":"hile"},{"SteamID":76561198170175423,"Username":"Cross","BanReason":"hile"},{"SteamID":76561198443082053,"Username":"Nameless","BanReason":"hile"},{"SteamID":76561198233935516,"Username":"kaujaro","BanReason":"oç"},{"SteamID":76561198394266321,"Username":"DonDraper","BanReason":"oç"},{"SteamID":76561198324173411,"Username":"sokucu","BanReason":"hile ölmüyor"},{"SteamID":76561199058806337,"Username":"Bersan","BanReason":"oç oyun bozan"},{"SteamID":76561198287765760,"Username":"Hararet","BanReason":"oç trol"},{"SteamID":76561198144690747,"Username":"BlackTreaty","BanReason":"hile"},{"SteamID":76561199266932888,"Username":"Senju","BanReason":"çocuk"},{"SteamID":76561198970594350,"Username":"Slayex","BanReason":"orospu çocuğu"},{"SteamID":76561199001696792,"Username":"dehatuzcu","BanReason":"hileci hız hilesi"},{"SteamID":76561199251125498,"Username":"captainkapar","BanReason":"oç"},{"SteamID":76561198833777458,"Username":"banditcampcomNIGGACAT","BanReason":"oç trol"},{"SteamID":76561198859245396,"Username":"PASİFNURETTİN","BanReason":"trol"},{"SteamID":76561199120841245,"Username":"Esatqw","BanReason":"oç trol hile"},{"SteamID":76561199214634293,"Username":"Pampanto","BanReason":"oç"},{"SteamID":76561199511776757,"Username":"baranesen","BanReason":"hile oç"},{"SteamID":76561199088338839,"Username":"YağızBayram","BanReason":"hile oç"},{"SteamID":76561198196128499,"Username":"Nameless","BanReason":"oç trol "},{"SteamID":76561198360668830,"Username":"EmirGT","BanReason":"trol"},{"SteamID":76561198906977594,"Username":"Lokal","BanReason":"çocuk hız bug"},{"SteamID":76561199525980445,"Username":"Xamion","BanReason":"hile"},{"SteamID":76561198914492939,"Username":"TEKLUCIFERBloodycasecom","BanReason":"trol oç"},{"SteamID":76561198170301055,"Username":"Parkour","BanReason":"hız bug hile"},{"SteamID":76561199568792692,"Username":"Daricwia","BanReason":"oç oy verdi"},{"SteamID":76561198433700555,"Username":"IRGIEralp","BanReason":"trol"},{"SteamID":76561199052192576,"Username":"Tolgaaaxd","BanReason":"hız bug"},{"SteamID":76561198181787695,"Username":"Atna","BanReason":"top"},{"SteamID":76561198443760904,"Username":"Belingool","BanReason":"trol vote attı"},{"SteamID":76561198317460558,"Username":"CONNOR","BanReason":"hile"},{"SteamID":76561199403018933,"Username":"Mark","BanReason":"çocuk"},{"SteamID":76561199502325071,"Username":"yigitk","BanReason":"oç"},{"SteamID":76561198832882902,"Username":"yusuf","BanReason":"gamethrower "},{"SteamID":76561198372603786,"Username":"BorsaKaplanı","BanReason":"hile"},{"SteamID":76561198838515576,"Username":"Mmh","BanReason":"hile"},{"SteamID":76561199041805716,"Username":"Synıox","BanReason":"hileci oç"},{"SteamID":76561199090363272,"Username":"Twizzist","BanReason":"gamethrower"},{"SteamID":76561199380830004,"Username":"muhammed","BanReason":"hile"},{"SteamID":76561199061238402,"Username":"Mealez","BanReason":"ban trol hile"},{"SteamID":76561198294484941,"Username":"py","BanReason":"ban trol hile"},{"SteamID":76561199092347291,"Username":"py","BanReason":"ban trol hile"},{"SteamID":76561198200559558,"Username":"zort","BanReason":"No reason given"},{"SteamID":76561198845808436,"Username":"namelesskral","BanReason":"No reason given"},{"SteamID":76561198423149813,"Username":"EKYILDIZ","BanReason":"hile"}]}"
`

**Comment by gamendegamer321** [comment]
This is unfortunately not something I'm planning on adding as it would require me to host a public ban record and moderate the ban list.

I don't think a community moderated ban list is possible where, if 10 players ban somebody, they get banned from all servers, as this brings the problem of people having different rules while playing and the possibility of banning somebody for no reason if you have a large enough group of friends and/or alt accounts.
