### ISSUE TITLE
Open admin UI conflicts with Better Lobbies

### ISSUE THREAD

**Issue by DeCat4** [gamendegamer321/Lethal-Admin#19]
I know it's not possible to make it so the mod doesn't conflict with every other mod but is there a possibility a setting can be added to change the offset of the open admin UI button or something? or have the button on the right side.
I apologize if i'm being entitled, selfish or anything, it's not a big problem and i understand if there won't be anything added to change this

![image](https://github.com/gamendegamer321/Lethal-Admin/assets/57727851/9793c732-52a9-4bd2-ab96-3ae2485ba859)

**Comment by gamendegamer321** [comment]
Moved the button down in 1.7.0. If there are more UI conflicts feel free to create a new issue or reopen this one!

**Comment by DeCat4** [comment]
thank you so much <3
