### ISSUE TITLE
Feature: Open steam profile

### ISSUE THREAD

**Issue by Ambushfall** [gamendegamer321/Lethal-Admin#2]
Possibility to implement an open profile option based on the steam id.

I believe this to be a great option for this tool.

If any further information is required, please advise.

**Comment by Ambushfall** [comment]
This is addressed in PR #3

**Comment by Niken-IT** [comment]
+ add change people volume level

**Comment by gamendegamer321** [comment]
You can already change someones volume level in the ingame pause menu (in the blue box in the image below). I feel this is better left to the game itself as I don't see any real benefits to having a second volume controller.

_(Same message as in the pull request regarding opening steam profiles, #3 )_
I don't really see a reason for adding this as it's already part of the base game. You can open someones profile by pressing the button next to their name in the pause menu (circled in red in the image), and as far as I know this still works with mods like BiggerLobby.

![image](https://github.com/gamendegamer321/Lethal-Admin/assets/74590966/c4758969-0532-40e7-84ce-1929fe62e81a)
