### ISSUE TITLE
[Bug] Menu button overlaps with the "Resume" button

### ISSUE THREAD

**Issue by IAmSympathy** [gamendegamer321/Lethal-Admin#20]
![image](https://github.com/gamendegamer321/Lethal-Admin/assets/110695959/235c913d-f355-4cf6-b02d-b69478d26a90)

Logs : 
[LogOutput.log](https://github.com/gamendegamer321/Lethal-Admin/files/15125166/LogOutput.log)

Profile code : 018f1898-fa31-1259-8008-f2d23a09e7b8

**Comment by IAmSympathy** [comment]
Relunched the game and look likes the "Open Admin UI" button completely dissapeared.

**Comment by gamendegamer321** [comment]
Ah, I moved the button down to prevent conflicts with another mod. I've now added a config option so you can set where the button appears yourself. By default it should also appear above the resume button now.
