### ISSUE TITLE
[Issue] minVotes feature break ship depart vote again

### ISSUE THREAD

**Issue by CoolLKKPS** [gamendegamer321/Lethal-Admin#23]
same as topic, and once again, still cannot believe no one found this issue in almost 5 days

**Comment by CoolLKKPS** [comment]
@gamendegamer321

**Comment by gamendegamer321** [comment]
Ah interesting, there shouldn't be any changes to how that works so it's a bit unexpected it broke.
I assume the ship does not depart after the threshold has been reached? I'll try to reproduce it.

**Comment by gamendegamer321** [comment]
I'm unable to reproduce it breaking. For me it seems to be working fine, can you maybe provide me with steps to reproduce the problem?

**Comment by CoolLKKPS** [comment]
modpack onedrive share link: Dark Hour<https://1drv.ms/f/s!AlwrljXcImfClQt9MgB2BOZ-XA9h>

**Comment by CoolLKKPS** [comment]
if u have enough more memory (30GB), u need 3 clients to reproduce, minvote set to 2, gl

**Comment by gamendegamer321** [comment]
I'm having issues with the pack where I can't run multiple instances, and I'm unable to join my LAN session. I'll try to test a few mods separately, I suspect it's an anti-cheat or something similar.

**Comment by CoolLKKPS** [comment]
unable to join LAN session is a known issue with anticheat by chuxiaaaa

**Comment by gamendegamer321** [comment]
I think I've found the issue, I think it's a conflict with [HostFixes](https://github.com/Charlese2/HostFixes). If you use hostfixes you can use their version of the minVotes by going into the config for hostfixes and setting the <code>Minimum Votes To Leave Early</code> to the value you want, then set the minVotes for lethal admin to 1 to prevent the conflict.
