### ISSUE TITLE
[Bug] Kicks/Bans affecting the wrong players

### ISSUE THREAD

**Issue by DeCat4** [gamendegamer321/Lethal-Admin#24]
the host of the server i often play on needs to kick cheaters and sometimes it ends up affecting someone else entirely, when i'm kicked it says the host disconnected

**Comment by gamendegamer321** [comment]
When kicking there is a check for both the username and steam ID of the user being kicked. Only the players matching both will be kicked and disconnected. 
The kicking is, in the end, still done by the game itself. So, I'm a bit confused how this even happens.

Would it be possible to get a clip of this happening, or the steam ID and username of the cheater and the person actually being kicked (including the generated log(s) in the <code>Settings & Logs</code> tab)?

And if I'm not mistaken, in the base game when you get kicked you also get the message that the host disconnected, I don't add a custom message so it shows the same.

**Comment by DeCat4** [comment]
i'll try to get a clip next time this happens but i was looking at the host's stream, they banned someone then i got disconnected but i was able to rejoin, it could've just been a coincidence but idk

**Comment by gamendegamer321** [comment]
I'll close the issue now, if you encounter it again feel free to reopen it.
