### ISSUE TITLE
Make whitelist affect the lever lock

### ISSUE THREAD

**Issue by DeCat4** [gamendegamer321/Lethal-Admin#26]
Sometimes i need to go afk and i'd like to let my friends handle the ship during that time

**Comment by DeCat4** [comment]
Sometimes i need to go afk and i'd like to let my friends handle the ship during that time

**Comment by gamendegamer321** [comment]
With the current implementation of the lever lock this is not possible. It might be possible if I take a different approach but I'm not sure yet.

**Comment by gamendegamer321** [comment]
Not possible with the current approach. The lever gets locked for all whitelisted people once someone who is not whitelisted attempts to make the ship depart.
