### ISSUE TITLE
Prevent spending money for non whitelisted.

### ISSUE THREAD

**Issue by DeCat4** [gamendegamer321/Lethal-Admin#27]
Setting to stop people from buying: Ship Upgrades, Items, Decors or Moons (all of these 4 as diff options) and only the host and whitelisted players can do, Lockdown does this already but it'd be nice to have a whitelist system and lockdown doesn't get support

**Comment by gamendegamer321** [comment]
Sorry for the _very_ late response.
I won't be adding this as it requires networking. I've stopped playing the game myself so I'm fine with maintaining and occasionally updating the mod. However using the networking is not something I'm willing to do anymore.
