### ISSUE TITLE
New cheats?

### ISSUE THREAD

**Issue by mrakrmakmrka** [gamendegamer321/Lethal-Admin#29]
Today (07.12.2024), a player came in that I can't ban, but could kick, causing the person to constantly come in. I've never seen that before. Can you fix it somehow?

**Comment by gamendegamer321** [comment]
That most definitely shouldn't happen. What did the in-game logs say? Whenever you ban someone it should say: <code>[Ban] XXXXX has been banned</code>. However if it fails it should also show a message with why the player could not be banned.

Banning uses the same system as kicking, unless the player has a SteamID of 0 in which case they can't get banned, so it's weird only kicking works and banning does nothing.

**Comment by mrakrmakmrka** [comment]
> That most definitely shouldn't happen. What did the in-game logs say? Whenever you ban someone it should say: `[Ban] XXXXX has been banned`. However if it fails it should also show a message with why the player could not be banned.
> 
> Banning uses the same system as kicking, unless the player has a SteamID of 0 in which case they can't get banned, so it's weird only kicking works and banning does nothing.

Where are the logs saved? And it's been 6 hours since then, if the logs are not saved anywhere, I won't be able to see them. But it's exactly like that, I clicked on the “ban” button, nothing happened, also that player was not displayed in the list of players on TAB, only in your mod it was displayed.

**Comment by gamendegamer321** [comment]
Unfortunately not, it has not really been needed and most of the things logged are just when a ban has been processed (which can also be seen in the ban tab).

My suspicion is that the player joined with a steam ID set to 0, the require steam setting should prevent players from joining without a steam ID, do you have the require steam setting enabled?

**Comment by mrakrmakmrka** [comment]
> Unfortunately not, it has not really been needed and most of the things logged are just when a ban has been processed (which can also be seen in the ban tab).
> 
> My suspicion is that the player joined with a steam ID set to 0, the require steam setting should prevent players from joining without a steam ID, do you have the require steam setting enabled?

It's on and has always been on. That's even more alarming. How could that person have gotten in?

**Comment by gamendegamer321** [comment]
Do you maybe remember if it showed a steam ID for the user? Or if it was set to 0?

If they had a steam ID and the ban did nothing, it may be that there was a problem saving their information in the ban. However without the logs it's kinda hard for me to say what exactly happened.

**Comment by mrakrmakmrka** [comment]
> Do you maybe remember if it showed a steam ID for the user? Or if it was set to 0?
> 
> If they had a steam ID and the ban did nothing, it may be that there was a problem saving their information in the ban. However without the logs it's kinda hard for me to say what exactly happened.

I don't remember. But all right, since there's nothing to be done, I'd better close it for now. If I come across a player like that, I'll even try to make a video showing the logs. Thanks for your time.
