### ISSUE TITLE
Reaching out

### ISSUE THREAD

**Issue by Ambushfall** [gamendegamer321/Lethal-Admin#6]
Recently, I wanted to reach out to you to consolidate our changes and to hopefully understand what the next improvements could be, I was unable to unfortunately.

It would certainly make it a lot easier if there was a point of contact where I could reach out to you to consult on the possible changes.

If this is something unwanted, that is entirely fine. I will continue comms via PR's or Issues.

**Comment by gamendegamer321** [comment]
You can reach me at gamendegamer321@gmail.com or gamendegamer321 on discord.

As for future plans, I'm planning on improving the UI as I feel like it's still a bit cluttered and seeing if it's possible to make other players moderators.
I've also not played the game in a while, so I don't really know if there are any other things people would like to see.

**Comment by Ambushfall** [comment]
I've added you on my discord.

Hopefully this helps out a bit dealing with comms.
