### ISSUE TITLE
Request: reqiure valid steam id to join

### ISSUE THREAD

**Issue by sword11247** [gamendegamer321/Lethal-Admin#8]
i know theres one for the lever but is it possible to add one to not allow players without a valid steam id

**Comment by gamendegamer321** [comment]
Is this similar to #7? (This already kicks players trying to join with their steam id set to 0, when using the latest version it should be enabled automatically)

Or are you talking about players joining with other steam ids?

**Comment by sword11247** [comment]
i think i confused valid steam id with the lever as i thought it didn't allow them to land the ship but i think i had host can only land on at the same time
